[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn", "python3"]

[phases.install]
cmds = ["cd backend && npm install --production=false"]

[phases.build]
cmds = ["cd backend && npm run build || echo 'Build script not required'"]

[start]
cmd = "cd backend && npm start"