name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Test Backend
        run: |
          cd backend
          npm install
          echo "✅ Backend dependencies installed"

      - name: Deploy Success
        run: |
          echo "✅ Ready for Railway deployment"
          echo "📦 Code pushed to GitHub"
          echo "🚀 Railway will auto-deploy from GitHub"